### PR TITLE
feat: add option for emitting keys

### LINKED ISSUE #76: How to parse root-level props or how to get parent key in data event

### PR DESCRIPTION
**Pull request by joscha**
This adds the option to emit keys out of the stream.

closes #76.

### CODE REVIEW

**Comment by dogfoodsilo4** [comment]
Tested this and it works great.

**Comment by joscha** [comment]
That's great to hear @dogfoodsilo4 - @dominictarr any chance of getting this merged?

**Comment by dominictarr** [comment]
hey, sorry I didn't see this. I have lots of modules and get lots of issues so sometimes I don't have the bandwidth to deal with something and it slips down the inbox.

**Comment by dominictarr** [comment]
merged into 1.1.0

**Comment by dominictarr** [comment]
sorry, make that 1.1.1

**Comment by joscha** [comment]
nice! Thank you!

**Comment by dogfoodsilo4** [comment]
Awesome, thanks guys!

**Pull request merged**
