### PR TITLE
Remove trailing comma, to fix JSON parsing.

### PR DESCRIPTION
**Pull request by adamgaynor**
NPM fails to parse this JSON file when running `npm install`.

### CODE REVIEW

**Comment by dominictarr** [comment]
what npm version is this? that is actuall couchdb output that has been in this repo forever this is a bug in npm

**Comment by dominictarr** [comment]
what npm version? I am unable to reproduce this with either npm 3.8 or 4.0.2

**Comment by adamgaynor** [comment]
I had an issue running NPM 1.3.10, with node 0.10.25.

Everything worked fine until a few days ago, when NPM started throwing `npm ERR! registry error parsing json`, so this may not be the actual cause of the error.

I realize this is an older version of NPM, but figure that fixing a syntax error is never a bad thing.

**Comment by dominictarr** [comment]
I'm doubtful that this file is the cause of your error. Npm shouldn't even parse that file while installing.
using nvm, I tried node 0.10.25, with npm 1.3.24 and installed this fine, same with node 0.10.48 and npm 2.15.1

My bet is that what you are getting is either the registry giving an invalid response (or something breaking it) or your cache.

**Comment by adamgaynor** [comment]
It does look like that was the case, with the registry giving an invalid response.
Updating node and npm also fixed the issue, thank you for the suggestion!

**Pull request closed without merging**
