### PR TITLE
fix memory leak problem when streaming huge files

### LINKED ISSUE #153: Memory leak regression in 1.3.3
I use JSONStream to parse large GeoJSON files and stream them to a database.

In the last version, parsing a large GeoJSON feature collection fails due to an out of memory error.

This happens because of a memory leak introduced in version 1.3.3. Version 1.3.2 works fine.

In particular, this commit is the culprit:

https://github.com/dominictarr/JSONStream/commit/8c1206e2ab2e069997d105cedc966efd80eefa57#diff-168726dbe96b3ce427e7fedce31bb0bcL118

Re-adding the line "delete this.value[this.key]" fixes the problem.

### PR DESCRIPTION
**Pull request by daern91**
PR reverts commits [2e4fcb](https://github.com/dominictarr/JSONStream/commit/2e4fcb2d701aa612405102c2b5a0382842fdd318) and [8c1206](https://github.com/dominictarr/JSONStream/commit/8c1206e2ab2e069997d105cedc966efd80eefa57) that introduced memory leaks.

Please squash merge.

resolves #153

### CODE REVIEW

**Comment by dominictarr** [comment]
@mfogel looks like this change will break your code?

**Comment by mfogel** [comment]
@dominictarr yeah I think so. This would re-open #148 

Seems that it should be possible to fix this memory leak issue without re-breaking the double-dot operator.

**Comment by daern91** [comment]
My bad, I missed the earlier issue. Anyways, thanks guys, @dominictarr and @mfogel. Updated the PR now to fix memory leak without reverting @mfogel's fixes.

**Comment by daern91** [comment]
Any update here @dominictarr?

**Comment by ruettenm** [comment]
It would be nice to merge this PR :-)

**Comment by mfogel** [comment]
As far as I can see, the PR now looks ok to me.

**Comment by dominictarr** [comment]
@daern91 hey, sorry for the delay. would you be willing to help maintain this module? I don't really even use it anymore, and have lots of other things to do with my time. I can add you and you can merge this

**Comment by dominictarr** [comment]
@daern91 there arn't many issues/PRs, it's just that I have loads of other stuff

**Comment by dominictarr** [comment]
@daern91 you can now merge and publish

**Pull request merged**
