### PR TITLE
Emit error events on unvalid JSON stream

### PR DESCRIPTION
**Pull request by gchauvet**
Emit error events on unvalid JSON stream described in ticket #66

### CODE REVIEW

**Comment by dominictarr** [comment]
this isn't the right solution. The parser already has an onError listener, and that calls `stream.emit('error', err)` but for some reason that isn't working. Need to figure out why that is, not wrap a try-catch around write.

**Comment by gchauvet** [comment]
Okay, I need to check jsonparse library:  the parser is stopped by the raised of an exception in the original onError method. Overriding onError break the error processing (that's why we have multiple parse errors in this patch).

Work in progress on jsonparse...

**Comment by dominictarr** [comment]
hmm, oh i think the problem is that it calls the error without return.
So the throw will break the parse loop, but if it is handled it will just continue...
what it needs `return` to be added ahead of each call to  `this.charError` etc

**Comment by gchauvet** [comment]
Done on my jsonparse fork. I will test this weekend

**Comment by gchauvet** [comment]
Need  to fix single error emitting. come in soon

**Comment by gchauvet** [comment]
Okay, this is done. Now JSONStream emit a single error event.
Waiting a feedback from jsonparse's maintainer about my changes.

**Comment by gchauvet** [comment]
jsonparse 1.1.x has been released on npmjs.

**Comment by dominictarr** [comment]
Okay I'll merge this, but by the way, you should not bump the version in a pull request, that for a decision for the maintainer. there may be other pull requests that are also being merged, and they may also have a way they do it. (e.g, i always do it in it's own commit, so that it's easy to look at git log and see where the commits are.)

**Comment by dominictarr** [comment]
merged into 1.0.6

**Pull request merged**
