### PR TITLE
Implement header (and footer) support

### PR DESCRIPTION
**Pull request by doowb**
This PR implements emitting a `header` and `footer` event with data that comes before and after the specified path. This is implemented in a way that when the specified path is first found, if the header object has been populated, it's emitted immediately so the entire document doesn't need to be read in.

The footer contains the remaining properties (if any) after the values in the specified path have been exhausted. I believe my logic is correct since the current tests are still passing.

I think this address #99 and #93.

I tried to keep with the current coding style, so please let me know if there is something that I need to change.

Thanks!

### CODE REVIEW

**Comment by dominictarr** [comment]
thanks this looks like a great pull request, will merge. do you mind if I also add you as a collaborator?

**Comment by doowb** [comment]
> do you mind if I also add you as a collaborator?

I don't mind, that'd be great. I'm happy to help out where I can.

**Comment by dominictarr** [comment]
awesome, you are now also a collaborator and npm owner,
merged into 1.2.1

**Comment by jcready** [comment]
Can someone explain how we can use these new header/footer events to take a JSON data like in #93 and pipe it to a write stream such that I can modify each object in the `records` array but also include the rest of the top-level properties in the final output piped to the write stream?

**Pull request merged**
