### PR TITLE
Ignore 'test' in npmignore

### PR DESCRIPTION
**Pull request by zertosh**
Please consider excluding the "test" dir from the published package. They're 500k (granted not much), but packages like browserify include it about 5 times through its various dependencies.

### CODE REVIEW

**Comment by zertosh** [comment]
@dominictarr Can you publish 1.x to npm please? (https://github.com/dominictarr/JSONStream/compare/7ae00aa...a85a00a)

**Comment by KenanY** [comment]
@zertosh https://github.com/dominictarr/JSONStream/issues/59

**Comment by zertosh** [comment]
Thanks @KenanY! I'll leave this open just for the npmignore change - for when it's possible to update

**Comment by dominictarr** [comment]
browserify does not include the tests in the bundle. I always leave the tests in my modules because one day it might be useful to be able to run all the tests from npm...

**Pull request closed without merging**
